### ISSUE TITLE
ERROR in multi @babel/polyfill

### ISSUE THREAD

**Issue by Himself65** [luogu-dev/luogu-blog-frontend#41]
```bash
yarn run v1.15.2
$ npm run build-dev && npm run dev-server

> luogu-blog-frontend@1.0.0 build-dev C:\Users\himself65\Desktop\Github\luogu-blog-frontend
> cross-env NODE_ENV=development webpack --progress --hide-modules --mode development

                                                                                                  1
                                                                                                2
                                                                                                3
                                                                                                3
                                                                                                4
                                                                                                5
                                                                                                6
         Hash: 855b9ac7194326217292
Version: webpack 4.15.1
Time: 42770ms
Built at: 2019-04-30 18:13:33
                                             Asset      Size        Chunks                    Chunk Names
                                             52.js  14.4 KiB            52  [emitted]
              c67be87adba7d31c013be127b936233d.ttf  69.8 KiB                [emitted]
            3d8245dcb4489694a6a263b05c1cca01.woff2  32.4 KiB                [emitted]
              3f61a84d76e80396489d32bc9dd8d444.ttf  19.1 KiB                [emitted]
             445f96a387df0d13ded71f27c608516d.woff  11.9 KiB                [emitted]
            970d3e76493b82fccf21ad5888ddee77.woff2  10.4 KiB                [emitted]
              c3bc8fcec0e85a50cabf71e4e8074991.ttf  18.5 KiB                [emitted]
             74f6918c7d2b768ffd32048102bc0172.woff  11.6 KiB                [emitted]
            0ef0f2e356a2e1c457b6585d34edae77.woff2  10.2 KiB                [emitted]
              e11e6bf02fc41279a540d3655abf3b07.ttf  35.1 KiB                [emitted]
             1aca7ef7f976fb54a207ffc8aa180e38.woff  22.8 KiB                [emitted]
            950649ba5e5cfd37cdad74095411d350.woff2    20 KiB                [emitted]
              a9509497466d16e6b7265a223ea39093.ttf  33.8 KiB                [emitted]
             c5b430bfcb3e5423b77401afcdb69b66.woff  22.3 KiB                [emitted]
            135ccd74931753318f6f52f3fce19018.woff2  19.4 KiB                [emitted]
              aaaa1b761b7cc9d5e10b85f30731b878.ttf  60.3 KiB                [emitted]
             0ba875a1d548ebfdd00c7594022e01b7.woff  36.1 KiB                [emitted]
            c5b67fb3f6bdaa7f2dd75e5bc8d929eb.woff2  30.1 KiB                [emitted]
              bdbadb27e05fb8e51da903db59f90d77.ttf  43.8 KiB                [emitted]
             5aeca883bc41b522fdf1409ee912b51c.woff  25.6 KiB                [emitted]
            0719833c23aeba83786a29e84a165875.woff2  21.7 KiB                [emitted]
              2155d7897af94033a6b6ed44133b867e.ttf  46.8 KiB                [emitted]
             bb7c45db8908c8fb88a293895a64e018.woff  26.6 KiB                [emitted]
            6bf616283a81e40e4ac755883862b472.woff2  22.5 KiB                [emitted]
              7b8d1fa0668e317c4a2d34399e74af25.ttf  68.9 KiB                [emitted]
             1fd21713706a2b70960faf21b1fa4e26.woff  38.8 KiB                [emitted]
            29b27903a08a71f8171be21ba413d4dd.woff2  32.3 KiB                [emitted]
              10740d7488d690a743339650103f1cb3.ttf  40.5 KiB                [emitted]
             8eb56b3ff5b141cd3732a24e65c2b339.woff  23.3 KiB                [emitted]
            7a31741a44e58952cb4b8a763c206fcd.woff2  19.9 KiB                [emitted]
              9123667cef81279761df5cd62ec8c46e.ttf  33.2 KiB                [emitted]
             84299b016163b0ae5c776604aa1cb726.woff  18.7 KiB                [emitted]
            e38d0f6844b9520510715fd989bdd5bd.woff2  15.6 KiB                [emitted]
              f9c440abdd25c5a954d855516fed39f9.ttf  30.6 KiB                [emitted]
             95c5a3d43efbcb8c14184d00a7c5eed4.woff  17.7 KiB                [emitted]
            1057b70228cb6936e7714e7817db6ce2.woff2  14.8 KiB                [emitted]
              2eae604dbbc4b2c0ceede62c61c9e8df.ttf  29.4 KiB                [emitted]
             35bda414c6c2f75940b086de18f42e72.woff  16.4 KiB                [emitted]
            f9e06d59e70de05c5f0b7f7f65c14565.woff2  13.7 KiB                [emitted]
              e9169ca7b32608b6235ec9ffff742a71.ttf  24.3 KiB                [emitted]
             60febfa114c5e32f0ce73050476aa39f.woff  13.5 KiB                [emitted]
            ae1fad1f4d1c227c9d567da8ea9f988c.woff2    12 KiB                [emitted]
              f2e296ef7cef0f6f16912e5d171929b2.ttf  12.9 KiB                [emitted]
             1d6cf6b89f694dc76e13ecc4e8214dd2.woff  6.82 KiB                [emitted]
            fda0824e8cfb676664ad063c367cfce3.woff2  5.68 KiB                [emitted]
              0767ede65042583bcc06f09055f4d7ca.ttf  12.1 KiB                [emitted]
             f48e83b7bcaa68a86a78e8edfee1a04e.woff  6.53 KiB                [emitted]
            a7a0eb93afb696cb9b4efb87e6cd45a3.woff2  5.43 KiB                [emitted]
              882f723427a0986846fe786bd8d6f6c7.ttf  8.16 KiB                [emitted]
             0387ab387ace32f15b43c3a4a39f187f.woff  4.66 KiB                [emitted]
            397bd6872be7adff4f000c49fa85a9c3.woff2  3.77 KiB                [emitted]
              27901d5ce93d8971c416d9123fedb911.ttf    11 KiB                [emitted]
             726db3bd435c8a6e45e44741dae67263.woff   6.3 KiB                [emitted]
            3c14ed11dd8eea981c93bf283193856d.woff2  5.01 KiB                [emitted]
              6b9645af6e119fd5d85f24e21044ed03.ttf  35.5 KiB                [emitted]
             ba01f72a8db89265149f3f712dc7f9a3.woff  20.4 KiB                [emitted]
            f43e86963e9cfda37bb2e958ddedcaad.woff2  17.1 KiB                [emitted]
              13db00b7a34fee4d819ab7f9838cc428.eot  96.3 KiB                [emitted]
              a1a749e89f578a49306ec2b055c073da.svg   496 KiB                [emitted]  [big]
  brand-icons.svg?717c8a0c3865298b8b36a18be518e34f  82 bytes                [emitted]
              c5ebe0b32dc1b5cc449a76c4204d13bb.ttf  96.1 KiB                [emitted]
             a046592bac8f2fd96e994733faf3858c.woff  62.2 KiB                [emitted]
            e8c322de9658cbeb8a774b6624167c2c.woff2  53.2 KiB                [emitted]
              8e3c7f5520f5ae906c6cf6d7f3ddcd19.eot   104 KiB                [emitted]
              962a1bf31c081691065fe333d9fa8105.svg   382 KiB                [emitted]  [big]
        icons.svg?4d8475c4956ead1ded758675f0e6d184  82 bytes                [emitted]
              b87b9ba532ace76ae9f6edfe9f72ded2.ttf   103 KiB                [emitted]
             faff92145777a3cbaf8e7367b4807987.woff  49.3 KiB                [emitted]
            0ab54153eeeca0ce03978cc463b257f7.woff2  39.2 KiB                [emitted]
              701ae6abd4719e9c2ada3535a497b341.eot  30.4 KiB                [emitted]
              82f60bd0b94a1ed68b1e6e309ce2e8c3.svg   105 KiB                [emitted]
outline-icons.svg?39dc361a17b76733569d7ddb357c27e4  82 bytes                [emitted]
              ad97afd3337e8cda302d10ff5a4026b8.ttf  30.2 KiB                [emitted]
             ef60a4f6c25ef7f39f2d25a748dbecfe.woff  14.4 KiB                [emitted]
            cd6c777f1945164224dee082abaea03a.woff2    12 KiB                [emitted]
        flags.png?9c74e172f87984c48ddf5c8108cabe67  27.5 KiB                [emitted]
                                              0.js  49.8 KiB             0  [emitted]
                                        article.js  8.87 KiB       article  [emitted]         article
                                              2.js  39.7 KiB             2  [emitted]
                                              3.js  35.3 KiB             3  [emitted]
                                              4.js  80.9 KiB             4  [emitted]
                                              5.js    46 KiB             5  [emitted]
                                              6.js  80.7 KiB             6  [emitted]
                                              7.js   151 KiB             7  [emitted]
                                              8.js  32.2 KiB             8  [emitted]
                                              9.js  39.1 KiB             9  [emitted]
                                             10.js  25.1 KiB            10  [emitted]
                                             11.js   125 KiB            11  [emitted]
                                             12.js  9.02 KiB            12  [emitted]
                                             13.js  6.59 KiB            13  [emitted]
                                             14.js  5.97 KiB            14  [emitted]
                                             15.js  7.91 KiB            15  [emitted]
                                             16.js  6.79 KiB            16  [emitted]
                                             17.js  7.22 KiB            17  [emitted]
                                             18.js  15.2 KiB            18  [emitted]
                                             19.js  5.18 KiB            19  [emitted]
                                             20.js   1.4 KiB            20  [emitted]
                                             21.js  7.03 KiB            21  [emitted]
                                             22.js  4.52 KiB            22  [emitted]
                                             23.js  13.6 KiB            23  [emitted]
                                             24.js   5.3 KiB            24  [emitted]
                                             25.js  7.05 KiB            25  [emitted]
                                             26.js  3.35 KiB            26  [emitted]
                                             27.js  4.47 KiB            27  [emitted]
                                             28.js  6.82 KiB            28  [emitted]
                                             29.js  2.95 KiB            29  [emitted]
                                             30.js  2.81 KiB            30  [emitted]
                                             31.js  12.3 KiB            31  [emitted]
                                             32.js  3.07 KiB            32  [emitted]
                                             33.js  24.8 KiB            33  [emitted]
                                             34.js   3.9 KiB            34  [emitted]
                                             35.js  8.25 KiB            35  [emitted]
                                             36.js  6.17 KiB            36  [emitted]
                                             37.js  4.24 KiB            37  [emitted]
                                             38.js  5.54 KiB            38  [emitted]
                                             39.js  1.61 KiB            39  [emitted]
                                             40.js  18.2 KiB            40  [emitted]
                                             41.js  5.36 KiB            41  [emitted]
                                             42.js  13.3 KiB            42  [emitted]
                                             43.js   7.6 KiB            43  [emitted]
                                             44.js  9.67 KiB            44  [emitted]
                                             45.js  11.8 KiB            45  [emitted]
                                             46.js  13.8 KiB            46  [emitted]
                                             47.js  4.16 KiB            47  [emitted]
                                             48.js  17.6 KiB            48  [emitted]
                                             49.js  4.53 KiB            49  [emitted]
                                             50.js  4.42 KiB            50  [emitted]
                                             51.js  5.45 KiB            51  [emitted]
             ac1d46d953d403677171697581a284d2.woff  39.3 KiB                [emitted]
                                             53.js  3.82 KiB            53  [emitted]
                                             54.js  8.23 KiB            54  [emitted]
                                             55.js  7.22 KiB            55  [emitted]
                                             56.js  14.3 KiB            56  [emitted]
                                             57.js  3.45 KiB            57  [emitted]
                                             58.js  4.49 KiB            58  [emitted]
                                             59.js  2.75 KiB            59  [emitted]
                                             60.js  9.46 KiB            60  [emitted]
                                             61.js    18 KiB            61  [emitted]
                                             62.js  6.14 KiB            62  [emitted]
                                             63.js  10.3 KiB            63  [emitted]
                                             64.js  5.43 KiB            64  [emitted]
                                             65.js    14 KiB            65  [emitted]
                                             66.js  3.58 KiB            66  [emitted]
                                             67.js  7.56 KiB            67  [emitted]
                                             68.js  5.42 KiB            68  [emitted]
                                             69.js  6.69 KiB            69  [emitted]
                                             70.js   9.1 KiB            70  [emitted]
                                             71.js  15.2 KiB            71  [emitted]
                                             72.js  3.59 KiB            72  [emitted]
                                             73.js  5.84 KiB            73  [emitted]
                                             74.js  7.43 KiB            74  [emitted]
                                             75.js  11.1 KiB            75  [emitted]
                                             76.js  9.13 KiB            76  [emitted]
                                             77.js  5.93 KiB            77  [emitted]
                                             78.js  2.28 KiB            78  [emitted]
                                             79.js  2.88 KiB            79  [emitted]
                                             80.js  10.7 KiB            80  [emitted]
                                             81.js     8 KiB            81  [emitted]
                                             82.js  8.75 KiB            82  [emitted]
                                             83.js  7.55 KiB            83  [emitted]
                                             84.js  6.11 KiB            84  [emitted]
                                             85.js  7.81 KiB            85  [emitted]
                                             86.js  9.39 KiB            86  [emitted]
                                             87.js  12.3 KiB            87  [emitted]
                                             88.js  24.7 KiB            88  [emitted]
                                             89.js  7.38 KiB            89  [emitted]
                                              1.js  24.7 KiB             1  [emitted]
                                             91.js  3.18 KiB            91  [emitted]
                                             92.js  2.19 KiB            92  [emitted]
                                             93.js  13.6 KiB            93  [emitted]
                                             94.js  13.8 KiB            94  [emitted]
                                             95.js  18.8 KiB            95  [emitted]
                                             96.js  3.07 KiB            96  [emitted]
                                             97.js  3.36 KiB            97  [emitted]
                                             98.js  4.13 KiB            98  [emitted]
                                             99.js  14.1 KiB            99  [emitted]
                                            100.js  9.51 KiB           100  [emitted]
                                            101.js    14 KiB           101  [emitted]
                                            102.js  4.94 KiB           102  [emitted]
                                            103.js   4.5 KiB           103  [emitted]
                                            104.js  11.1 KiB           104  [emitted]
                                            105.js  3.47 KiB           105  [emitted]
                                            106.js  5.46 KiB           106  [emitted]
                                            107.js  9.84 KiB           107  [emitted]
                                            108.js  9.84 KiB           108  [emitted]
                                            109.js  8.78 KiB           109  [emitted]
                                            110.js  3.33 KiB           110  [emitted]
                                            111.js  7.77 KiB           111  [emitted]
                                            112.js  8.98 KiB           112  [emitted]
                                            113.js   5.3 KiB           113  [emitted]
                                            114.js  2.66 KiB           114  [emitted]
                                            115.js  4.72 KiB           115  [emitted]
                                            116.js  23.9 KiB           116  [emitted]
                                            117.js  3.06 KiB           117  [emitted]
                                            118.js  6.15 KiB           118  [emitted]
                                            119.js  12.9 KiB           119  [emitted]
                                            120.js  5.23 KiB           120  [emitted]
                                            121.js  13.1 KiB           121  [emitted]
                                            122.js  3.61 KiB           122  [emitted]
                                            123.js  2.45 KiB           123  [emitted]
                                            124.js  13.3 KiB           124  [emitted]
                                            125.js  10.4 KiB           125  [emitted]
                                            126.js  3.71 KiB           126  [emitted]
                                            127.js  1.57 KiB           127  [emitted]
                                            128.js     6 KiB           128  [emitted]
                                            129.js  7.43 KiB           129  [emitted]
                                            130.js  2.73 KiB           130  [emitted]
                                            131.js   2.9 KiB           131  [emitted]
                                            132.js  7.65 KiB           132  [emitted]
                                            133.js  3.68 KiB           133  [emitted]
                                            134.js  4.95 KiB           134  [emitted]
                                            135.js  2.26 KiB           135  [emitted]
                                            136.js  6.56 KiB           136  [emitted]
                                            137.js  7.08 KiB           137  [emitted]
                                            138.js  3.53 KiB           138  [emitted]
                                            139.js  7.29 KiB           139  [emitted]
                                            140.js  7.58 KiB           140  [emitted]
                                            141.js  18.1 KiB           141  [emitted]
                                            142.js  8.24 KiB           142  [emitted]
                                            143.js  2.28 KiB           143  [emitted]
                                            144.js  14.7 KiB           144  [emitted]
                                            145.js  18.1 KiB           145  [emitted]
                                            146.js  7.01 KiB           146  [emitted]
                                            147.js  15.9 KiB           147  [emitted]
                                            148.js  14.4 KiB           148  [emitted]
                                            149.js    11 KiB           149  [emitted]
                                            150.js  11.1 KiB           150  [emitted]
                                            151.js  5.75 KiB           151  [emitted]
                                            152.js    12 KiB           152  [emitted]
                                            153.js  1.55 KiB           153  [emitted]
                                            154.js  2.66 KiB           154  [emitted]
                                            155.js  5.71 KiB           155  [emitted]
                                            156.js  4.43 KiB           156  [emitted]
                                            157.js   5.6 KiB           157  [emitted]
                                            158.js   2.9 KiB           158  [emitted]
                                            159.js  2.31 KiB           159  [emitted]
                                            160.js  6.23 KiB           160  [emitted]
                                            161.js  6.92 KiB           161  [emitted]
                                            162.js  3.51 KiB           162  [emitted]
                                            163.js  3.82 KiB           163  [emitted]
                                            164.js  7.54 KiB           164  [emitted]
                                            165.js  5.42 KiB           165  [emitted]
                                            166.js  12.4 KiB           166  [emitted]
                                            167.js  13.1 KiB           167  [emitted]
                                            168.js  12.2 KiB           168  [emitted]
                                            169.js  13.4 KiB           169  [emitted]
                                            170.js  9.14 KiB           170  [emitted]
                                            171.js  4.31 KiB           171  [emitted]
                                            172.js  17.2 KiB           172  [emitted]
                                            173.js  6.41 KiB           173  [emitted]
                                            174.js  3.26 KiB           174  [emitted]
                                            175.js   5.2 KiB           175  [emitted]
                                   article_list.js  6.16 KiB  article_list  [emitted]         article_list
                                         common.js  8.27 MiB        common  [emitted]  [big]  common
                                          katex.js   147 KiB         katex  [emitted]         katex
                                             90.js  13.5 KiB            90  [emitted]

ERROR in multi @babel/polyfill ./src/templates/debug/article_list.js
Module not found: Error: Can't resolve '@babel/polyfill' in 'C:\Users\himself65\Desktop\Github\luogu-blog-frontend'
 @ multi @babel/polyfill ./src/templates/debug/article_list.js +0

ERROR in multi @babel/polyfill ./src/templates/debug/article.js
Module not found: Error: Can't resolve '@babel/polyfill' in 'C:\Users\himself65\Desktop\Github\luogu-blog-frontend'
 @ multi @babel/polyfill ./src/templates/debug/article.js +0
```

**Comment by Himself65** [comment]
```txt
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\himself65\\Desktop\\Github\\luogu-blog-frontend\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-dev' ]
2 info using npm@6.1.0
3 info using node@v10.15.3
4 verbose run-script [ 'prebuild-dev', 'build-dev', 'postbuild-dev' ]
5 info lifecycle luogu-blog-frontend@1.0.0~prebuild-dev: luogu-blog-frontend@1.0.0
6 info lifecycle luogu-blog-frontend@1.0.0~build-dev: luogu-blog-frontend@1.0.0
7 verbose lifecycle luogu-blog-frontend@1.0.0~build-dev: unsafe-perm in lifecycle true
8 verbose lifecycle luogu-blog-frontend@1.0.0~build-dev: PATH: C:\Users\himself65\Desktop\Github\luogu-blog-frontend\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\himself65\Desktop\Github\luogu-blog-frontend\node_modules\.bin;C:\Users\HIMSEL~1\AppData\Local\Temp\yarn--1556619146640-0.7859712383116582;C:\Users\himself65\Desktop\Github\luogu-blog-frontend\node_modules\.bin;C:\Users\himself65\AppData\Local\Yarn\Data\link\node_modules\.bin;C:\Program Files\libexec\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\himself65\Desktop\Github\luogu-blog-frontend\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;%NVM_HOME%;%NVM_SYMLINK%;C:\Users\himself65\.cargo\bin;C:\Users\himself65\AppData\Local\Microsoft\WindowsApps;C:\Users\himself65\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\himself65\AppData\Local\Yarn\bin;C:\gpp\bin;C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1\bin;;C:\Users\himself65\AppData\Roaming\npm;C:\Users\himself65\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\depot_tools;
9 verbose lifecycle luogu-blog-frontend@1.0.0~build-dev: CWD: C:\Users\himself65\Desktop\Github\luogu-blog-frontend
10 silly lifecycle luogu-blog-frontend@1.0.0~build-dev: Args: [ '/d /s /c',
10 silly lifecycle   'cross-env NODE_ENV=development webpack --progress --hide-modules --mode development' ]
11 silly lifecycle luogu-blog-frontend@1.0.0~build-dev: Returned: code: 2  signal: null
12 info lifecycle luogu-blog-frontend@1.0.0~build-dev: Failed to exec build-dev script
13 verbose stack Error: luogu-blog-frontend@1.0.0 build-dev: `cross-env NODE_ENV=development webpack --progress --hide-modules --mode development`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\himself65\Desktop\Github\luogu-blog-frontend\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\himself65\Desktop\Github\luogu-blog-frontend\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid luogu-blog-frontend@1.0.0
15 verbose cwd C:\Users\himself65\Desktop\Github\luogu-blog-frontend
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\himself65\\Desktop\\Github\\luogu-blog-frontend\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-dev"
18 verbose node v10.15.3
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 2
22 error luogu-blog-frontend@1.0.0 build-dev: `cross-env NODE_ENV=development webpack --progress --hide-modules --mode development`
22 error Exit status 2
23 error Failed at the luogu-blog-frontend@1.0.0 build-dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by Himself65** [comment]
because switch to the wrong branch
